### ISSUE TITLE
[FEATURE] Date zone time in logs

### ISSUE THREAD

**Issue by bypper** [PowerDNS/weakforced#446]
I cannot see any option to configure my Country date zone (Spain) in wforce.conf.
I'm using a Docker container but I think it's the same with a physical config.

This is an log line:
```
...
│[2025-03-17 10:19:26,578] deleteBLEntry ip_bl: ip=39.152.193.72/32
...
```
But in my Country it's **11:19** hour.

I suppose Wforce _show UTC date always_.

**Comment by neilcook** [comment]
Check the clock on the server docker is running on.

**Comment by bypper** [comment]
Hi Neil,
Yes, another Containers show localtime when I run "docker logs" command.

```
# date
lun mar 17 11:55:16 CET 2025

```

**Comment by neilcook** [comment]
You need to give the container the correct timezone when starting it, e.g.:
```
docker run -e TZ=Europe/Amsterdam powerdns/wforce:v2.10.1 ...

**Comment by bypper** [comment]
Yes, I know.
I've defined already with my zone...

```
# docker inspect miwforce | grep TZ
                "TZ=Europe/Madrid",
```

**Comment by neilcook** [comment]
Ok, well if you've done that, then I'm not really sure I can  help anymore. When I change the timezone it logs the correct local time for me. And the code is clearly using localtime.

**Comment by bypper** [comment]
It looks its problem of _Alpine_ image from which this comes.
It's not configured "**/etc/localtime**" and "**/etc/timezone**" on which we can set our timezone, as we can read in this post:

[https://zeljic.com/blog/docker-alpine-set-timezone/](https://zeljic.com/blog/docker-alpine-set-timezone/)

If you could build the image with these features I would appreciate it.

**Comment by bypper** [comment]
It looks I don't have permissions.

Only **Collaborator** can do it.

**Comment by bypper** [comment]
Hi Neil,
I've set my **_Wforce docker container_** with my right TZ, but the container logs have UTC time.
I don't have permissions to create **/etc/timezone** and **/etc/localtime** into container but I've probed to share from host in my compose:
```
services:
  wforce:
    image: powerdns/wforce-minimal:v2.12.1
    container_name: miwforce
    environment:
      TZ: Europe/Madrid
    volumes:
      - "/alberto/docker/miwforce/wforce.conf:/etc/wforce/wforce.conf"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
...
```
```
~# docker exec -it miwforce cat /etc/timezone
Europe/Madrid
```

But docker logs follow with UTC time...

```
# date && docker logs miwforce | tail -2
vie jul  4 10:27:22 CEST 2025
[2025-07-04 08:27:03,780] addBLEntry ip_bl: ip=1.189.209.19/32 expire_secs=86400 reason="Attempted password brute forcing"
[2025-07-04 08:27:03,780] allowLog Brute forcing attack detected: Country prohibido: allow="-1" remote="1.189.209.19" login="edmodo" protocol="smtp" device_id="" session_id="" device_attrs={} attrs={} rattrs={pais="China" ip="1.189.209.19" }
```

I'm afraid nothing I can do will change this.
